name: Push Nuget Packages to GitHub Package Registry

on:
  push:
    branches:
      - master

env:
  BUILD_CONFIGURATION: "Release"
  DOTNET_VERSION: "5.0.x"
  GITHUB_PACKAGE_REGISTRY_URL: https://api.nuget.org/v3/index.json

jobs:
  gpr-build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Generate build number
        id: build_number
        uses: paulhatch/semantic-version@v4.0.2
        with:
          tag_prefix: "v"

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          source-url: ${{ env.GITHUB_PACKAGE_REGISTRY_URL }}
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: dotnet build and publish
        run: |
          dotnet restore
          dotnet build -c ${{ env.BUILD_CONFIGURATION }}
          dotnet pack -c ${{ env.BUILD_CONFIGURATION }}

      - name: nuget publish
        run: |
          dotnet nuget push BccMembers.Api.Client.Contracts/bin/Release/*.nupkg -k ${{ secrets.NUGET_API_KEY }} --skip-duplicate
          dotnet nuget push BccMembers.Api.Client/bin/Release/*.nupkg -k ${{ secrets.NUGET_API_KEY }} --skip-duplicate
