name: Push Contracts Nuget Package to GitHub Package Registry

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "*"

env:
  BUILD_CONFIGURATION: "Release"
  DOTNET_VERSION: "5.0.x"
  GITHUB_PACKAGE_REGISTRY_URL: https://nuget.pkg.github.com/bcc-code/index.json
  PROJECT: BccMembers.Api.Client.Contracts

jobs:
  gpr-build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          source-url: ${{ env.GITHUB_PACKAGE_REGISTRY_URL }}
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: dotnet build and publish
        run: |
          dotnet restore ${{env.PROJECT}}/${{env.PROJECT}}.csproj
          dotnet build ${{env.PROJECT}}/${{env.PROJECT}}.csproj --configuration '${{ env.BUILD_CONFIGURATION }}'
          dotnet pack ${{env.PROJECT}}/${{env.PROJECT}}.csproj -c '${{ env.BUILD_CONFIGURATION }}'

      - name: "nuget publish"
        run: dotnet nuget push ${{env.PROJECT}}/bin/Release/*.nupkg -k ${{ secrets.NUGET_API_KEY }}
